// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPLfrnVSWLxk-6lNlU2qKr6Kt3dL7T20g',
    appId: '1:1053670431296:web:58642828ba6ca3491c1da5',
    messagingSenderId: '1053670431296',
    projectId: 'mhma-faze',
    authDomain: 'mhma-faze.firebaseapp.com',
    storageBucket: 'mhma-faze.appspot.com',
    measurementId: 'G-673ES75GPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEV7aJiRTZgJj1SE7XguvNqlme16eViOE',
    appId: '1:1053670431296:android:495a087b4ab4a2d11c1da5',
    messagingSenderId: '1053670431296',
    projectId: 'mhma-faze',
    storageBucket: 'mhma-faze.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAac-CN8Q2dOa5SDPZJE7T3sAElsFODgF4',
    appId: '1:1053670431296:ios:3da3d1f88343e8771c1da5',
    messagingSenderId: '1053670431296',
    projectId: 'mhma-faze',
    storageBucket: 'mhma-faze.appspot.com',
    androidClientId: '1053670431296-shalughcgnhv5323h0dm7ja3n422hk6c.apps.googleusercontent.com',
    iosClientId: '1053670431296-7u8qcppphrs7c3gqphu480rtvh4h8659.apps.googleusercontent.com',
    iosBundleId: 'com.example.mhma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAac-CN8Q2dOa5SDPZJE7T3sAElsFODgF4',
    appId: '1:1053670431296:ios:3da3d1f88343e8771c1da5',
    messagingSenderId: '1053670431296',
    projectId: 'mhma-faze',
    storageBucket: 'mhma-faze.appspot.com',
    androidClientId: '1053670431296-shalughcgnhv5323h0dm7ja3n422hk6c.apps.googleusercontent.com',
    iosClientId: '1053670431296-7u8qcppphrs7c3gqphu480rtvh4h8659.apps.googleusercontent.com',
    iosBundleId: 'com.example.mhma',
  );
}
